name: allnotification
description: Displays notification with default ringtones & alarm, sets custom ringtones.
version: 1.0.2
homepage: https://github.com/amosogra/notification
repository: https://github.com/amosogra/notification.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^4.0.1+1

dev_dependencies:

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.floodcode.plugins.allnotification
        pluginClass: AllnotificationPlugin
      ios:
        pluginClass: AllnotificationPlugin